модуль 8, задание 1
js-tasks-ru/jsbasic-20220922_aleksansander-m pull request #13
Opened 2022-11-27 10:56 UTC by moshub-js

2022-11-27 10:57 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2022-11-27 10:59 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-11-28 04:42 UTC, koalex requested changes
Нужно решить **8-2**

2022-12-03 06:54 UTC, moshub-js commented
> Нужно решить **8-2**

Добрый день!
Можно уточнить как должна осуществляться фильтрация нужно убирать видимость (style.display = 'none') или каждый раз "переформировывать" карточки согласно фильтру?
Спасибо.

2022-12-03 10:21 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2022-12-03 10:22 UTC, moshub-js commented
> > Нужно решить **8-2**
> 
> Добрый день! Можно уточнить как должна осуществляться фильтрация нужно убирать видимость (style.display = 'none') или каждый раз "переформировывать" карточки согласно фильтру? Спасибо.

Разобрался.

2022-12-05 04:27 UTC, koalex approved these changes

2022-12-05 04:28 UTC, merged